# Generated by Django 3.2.6 on 2021-09-25 22:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.UUID('d5a4e8dc-7bfb-4f80-abb0-1950932d7bd4'), primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
